### ISSUE TITLE
vahingossa suljettu issue

### ISSUE THREAD

**Issue by luimu64** [Wintermetal/Forssa-Horisontissa#2]
taisit sulkea mun viimeisimmän issuen vahingossa #1

**Comment by Wintermetal** [comment]
![shut](https://user-images.githubusercontent.com/58077340/146361088-c48cd097-e951-4a5a-b654-6d3efeb1cb63.png)

**Comment by luimu64** [comment]
@Wintermetal sun pitää painaa new pull request, ei close issue

**Comment by luimu64** [comment]
tässä tutoriaali https://www.youtube.com/watch?v=rgbCcBNZcdQ
